/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gerenciador_de_vendas;

import java.sql.ResultSet;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LUISHENRIQUEMAICADES
 */
public class Menu_Clientes extends javax.swing.JFrame {

    private ClientesDAO clientesDAO;

    /**
     * Creates new form Menu_Clientes
     */
    public Menu_Clientes() {
        setSize(720, 980);
        setTitle("Menu de Clientes");
        setLocationRelativeTo(null);
        setResizable(false);
        initComponents();

        try {
            clientesDAO = new ClientesDAO();
            loadClientesData();
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Configurando o JFrame
        setSize(720, 980);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        // setLayout(null);

        // Criando o JPanel com imagem de fundo
        JPanel P = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
            }
        };
        P.setBounds(50, 50, 700, 873); // Define posição e tamanho
        P.setOpaque(false); // Torna o painel transparente
        P.setLayout(null); // Define layout absoluto no painel

        // Adiciona o painel ao JFrame
        getContentPane().add(P);

        // Configurando o fundo
        ImageIcon imagemBackground = new ImageIcon("src\\img\\MENU_CLIENTES.jpg");
        JLabel labelBackground = new JLabel(imagemBackground);
        labelBackground.setBounds(0, 0, 720, 980);

        // Adiciona o fundo como último elemento
        getContentPane().add(labelBackground);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela_Clientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cNomeTextField = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        cCriarButton = new javax.swing.JButton();
        cPagarButton = new javax.swing.JButton();
        cConsultarButton1 = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NOME:");

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("CADASTRO");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tabela_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Curso", "CPF", "Saldo"
            }
        ));
        jScrollPane1.setViewportView(Tabela_Clientes);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        jLabel1.setText("Informe o CPF do cliente");

        cNomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNomeTextFieldActionPerformed(evt);
            }
        });

        jToggleButton1.setBackground(new java.awt.Color(255, 0, 0));
        jToggleButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("X");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        cCriarButton.setBackground(new java.awt.Color(51, 102, 255));
        cCriarButton.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        cCriarButton.setForeground(new java.awt.Color(0, 0, 0));
        cCriarButton.setText("cadastrar");
        cCriarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCriarButtonActionPerformed(evt);
            }
        });

        cPagarButton.setBackground(new java.awt.Color(51, 102, 255));
        cPagarButton.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        cPagarButton.setForeground(new java.awt.Color(0, 0, 0));
        cPagarButton.setText("pagar");
        cPagarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPagarButtonActionPerformed(evt);
            }
        });

        cConsultarButton1.setBackground(new java.awt.Color(51, 102, 255));
        cConsultarButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        cConsultarButton1.setForeground(new java.awt.Color(0, 0, 0));
        cConsultarButton1.setText("consultar");
        cConsultarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cConsultarButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(cCriarButton)
                        .addGap(18, 18, 18)
                        .addComponent(cPagarButton)
                        .addGap(18, 18, 18)
                        .addComponent(cConsultarButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cNomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1)))))
                .addGap(0, 113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cNomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cCriarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cPagarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cConsultarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        appGV closeClientes = new appGV();
        closeClientes.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void cCriarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCriarButtonActionPerformed

        JTextField campoCpf = new JTextField(15);
        JTextField campoNome = new JTextField(15);
        JTextField campoCurso = new JTextField(15);

        JPanel painel = new JPanel();
        painel.setLayout(new GridLayout(3, 3, 5, 5));

        painel.add(new JLabel("CPF: "));
        painel.add(campoCpf);
        painel.add(new JLabel("Nome:"));
        painel.add(campoNome);
        painel.add(new JLabel("Curso:"));
        painel.add(campoCurso);

        int resultado = JOptionPane.showConfirmDialog(
                null,
                painel,
                "Cadastrar Cliente",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (resultado == JOptionPane.OK_OPTION) {

            String nome = campoNome.getText();
            String curso = campoCurso.getText();
            String cpf = campoCpf.getText();

            System.out.println("Nome: " + nome);
            System.out.println("Curso: " + curso);
            System.out.println("CPF: " + cpf);

            String addNome = nome;
            String addCurso = curso;
            String addCpf = cpf;
            double addSaldo = 0;

            if (addNome.isEmpty() || addCurso.isEmpty() || addCpf.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor preencha todos os campos", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                Clientes novoClientes = new Clientes(0, addNome, addCurso, addCpf, addSaldo);
                ClientesDAO clientesDao;

                try {
                    clientesDao = new ClientesDAO();
                    int res = clientesDao.InserirClientes(novoClientes);
                    if (res == 1) {
                        JOptionPane.showMessageDialog(this, "Cliente cadastrado com sucesso", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                        this.clearForm();
                        loadClientesData();
                    } else {
                        JOptionPane.showMessageDialog(this, "Erro ocorrido ao inserir o cliente", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Erro ocorrido ao inserir o cliente", "ERROR", JOptionPane.ERROR_MESSAGE);
                }

            }
        }


    }//GEN-LAST:event_cCriarButtonActionPerformed

    private void cPagarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPagarButtonActionPerformed
        
        int linhaSelecionada = Tabela_Clientes.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um cliente na tabela");
            return;
        }

        int idCliente = Integer.parseInt(Tabela_Clientes.getValueAt(linhaSelecionada, 0).toString());

        int confirmacao = JOptionPane.showConfirmDialog(this, "Deseja quitar TODAS as vendas deste cliente?", "Confirmação de Pagamento", JOptionPane.YES_NO_OPTION);

        if (confirmacao != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            VendasDAO vendasDAO = new VendasDAO();
            int totalApagadas = vendasDAO.pagarVendasPorCliente(idCliente);

            if (totalApagadas >= 0) {
                JOptionPane.showMessageDialog(this, "Pagamento realizado com sucesso!\nVendas quitadas: " + totalApagadas);

                loadClientesData();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao realizar pagamento");
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro de conexão com o banco");
        }
    }//GEN-LAST:event_cPagarButtonActionPerformed

    private void cNomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNomeTextFieldActionPerformed

    }//GEN-LAST:event_cNomeTextFieldActionPerformed

    private void cConsultarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cConsultarButton1ActionPerformed
        String cpf = cNomeTextField.getText();

        if (cpf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um CPF");
            return;
        }

        try {
            ResultSet rs = clientesDAO.consultarCPF(cpf);

            DefaultTableModel model = (DefaultTableModel) Tabela_Clientes.getModel();
            model.setRowCount(0);

            boolean encontrou = false;

            while (rs.next()) {
                encontrou = true;
                model.addRow(new Object[]{rs.getInt("id"), rs.getString("nome"), rs.getString("curso"), rs.getString("cpf"), rs.getDouble("saldo")});
            }

            if (!encontrou) {
                JOptionPane.showMessageDialog(this, "CPF não encontrado");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao consultar CPF");
        }
    }//GEN-LAST:event_cConsultarButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela_Clientes;
    private javax.swing.JButton cConsultarButton1;
    private javax.swing.JButton cCriarButton;
    private javax.swing.JTextField cNomeTextField;
    private javax.swing.JButton cPagarButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

    private void clearForm() {
        cNomeTextField.setText("");
    }

    private void loadClientesData() throws SQLException {
        ClientesDAO clientesDao = new ClientesDAO();
        List<Clientes> clientes = clientesDao.getClientes();
        String[][] data = new String[clientes.size()][5];

        for (int i = 0; i < clientes.size(); i++) {
            data[i][0] = String.valueOf(clientes.get(i).getCid());
            data[i][1] = clientes.get(i).getNome();
            data[i][2] = clientes.get(i).getCurso();
            data[i][3] = clientes.get(i).getCpf();
            data[i][4] = String.valueOf(clientes.get(i).getSaldo());
            System.out.println(clientes.get(i).getNome());
        }
        String[] nomeColuna = {"Id", "Nome", "Curso", "CPF", "Saldo"};
        Tabela_Clientes.setModel(new javax.swing.table.DefaultTableModel(data, nomeColuna));
    }
}
