/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gerenciador_de_vendas;

import java.sql.ResultSet;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author LUISHENRIQUEMAICADES
 */
public class Menu_Vendas extends javax.swing.JFrame {

    private ClientesDAO clientesDAO;

    /**
     * Creates new form Menu_Vendas
     */
    public Menu_Vendas() {
        setSize(720, 980);
        setTitle("Menu de Vendas");
        setLocationRelativeTo(null);
        setResizable(false);
        initComponents();

        // Configurando o JFrame
        setSize(720, 980);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        // setLayout(null);

        // Criando o JPanel com imagem de fundo
        JPanel P = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
            }
        };
        P.setBounds(50, 50, 700, 873); // Define posição e tamanho
        P.setOpaque(false); // Torna o painel transparente
        P.setLayout(null); // Define layout absoluto no painel

        // Adiciona o painel ao JFrame
        getContentPane().add(P);

        // Configurando o fundo C:\\Users\\LUISHENRIQUEMAICADES\\Documents\\NetBeansProjects\\Projeto integrador\\Gerenciador_de_Vendas\\src\\img\\MENU.jpg
        ImageIcon imagemBackground = new ImageIcon("src\\img\\MENU_VENDAS.jpg");
        JLabel labelBackground = new JLabel(imagemBackground);
        labelBackground.setBounds(0, 0, 720, 980);

        // Adiciona o fundo como último elemento
        getContentPane().add(labelBackground);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        vConsultarButton = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        vNomeTextField2 = new javax.swing.JTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        jLabel2.setText("Informe o CPF do cliente");

        vConsultarButton.setBackground(new java.awt.Color(51, 102, 255));
        vConsultarButton.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        vConsultarButton.setForeground(new java.awt.Color(0, 0, 0));
        vConsultarButton.setText("CONSULTAR");
        vConsultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vConsultarButtonActionPerformed(evt);
            }
        });

        jToggleButton1.setBackground(new java.awt.Color(255, 0, 0));
        jToggleButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("X");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        vNomeTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vNomeTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vNomeTextField2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(vConsultarButton)
                .addContainerGap(267, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 408, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vNomeTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(vConsultarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(356, 356, 356))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vConsultarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vConsultarButtonActionPerformed

        String cpf;
        cpf = vNomeTextField2.getText();

        
        if (cpf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um CPF");
            return;
        }

        try {
            ClientesDAO clientesDAO = new ClientesDAO();
            ResultSet rs = clientesDAO.consultarCPF(cpf);

            if (!rs.next()) {
                JOptionPane.showMessageDialog(this, "CPF não encontrado");
                return;
            }

            int idCliente = rs.getInt("id");
            String nome = rs.getString("nome");
            String curso = rs.getString("curso");

            abrirTelaVenda(idCliente, nome, curso, cpf);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao consultar CPF");
        }
    }//GEN-LAST:event_vConsultarButtonActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        appGV closeVendas = new appGV();
        closeVendas.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void vNomeTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vNomeTextField2ActionPerformed


    }//GEN-LAST:event_vNomeTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Vendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton vConsultarButton;
    private javax.swing.JTextField vNomeTextField2;
    // End of variables declaration//GEN-END:variables

    private void abrirTelaVenda(int idCliente, String nome, String curso, String cpf) throws SQLException {

        JTextField campoValor = new JTextField(10);

        JPanel painel = new JPanel();
        painel.setLayout(new GridLayout(4, 2, 5, 5));
        painel.add(new JLabel("CPF:"));
        painel.add(new JLabel(cpf));
        painel.add(new JLabel("Nome:"));
        painel.add(new JLabel(nome));
        painel.add(new JLabel("Curso:"));
        painel.add(new JLabel(curso));
        painel.add(new JLabel("Valor da venda:"));
        painel.add(campoValor);

        int resultado = JOptionPane.showConfirmDialog(this, painel, "Registrar Venda", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (resultado == JOptionPane.OK_OPTION) {

            if (campoValor.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informe o valor");
                return;
            }

            try {
                double valor = Double.parseDouble(campoValor.getText());

                VendasDAO vendasDAO = new VendasDAO();

                String dataAtual = new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date());

                int res = vendasDAO.inserirVenda(dataAtual, valor, idCliente);

                if (res == 1) {
                    JOptionPane.showMessageDialog(this, "Venda registrada com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao registrar venda");
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Valor inválido");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Erro no banco de dados");
            }
        }
    }
}
